// Mocks generated by Mockito 5.2.0 from annotations
// in fh_home_coding/test/models/area_model_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:fh_home_coding/api.dart' as _i2;
import 'package:fh_home_coding/types.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [Api].
///
/// See the documentation for Mockito's code generation for more information.
class MockApi extends _i1.Mock implements _i2.Api {
  MockApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<Map<String, dynamic>>> getAreas() => (super.noSuchMethod(
      Invocation.method(#getAreas, []),
      returnValue: Future<List<Map<String, dynamic>>>.value(
          <Map<String, dynamic>>[])) as _i3.Future<List<Map<String, dynamic>>>);
  @override
  _i3.Future<Map<String, dynamic>> addContact(
          {int? areaId,
          String? name,
          String? phone,
          String? email,
          int? priority}) =>
      (super.noSuchMethod(
              Invocation.method(#addContact, [], {
                #areaId: areaId,
                #name: name,
                #phone: phone,
                #email: email,
                #priority: priority
              }),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i3.Future<Map<String, dynamic>>);
  @override
  _i3.Future<void> removeContact({int? areaId, _i4.Contact? contact}) =>
      (super.noSuchMethod(
          Invocation.method(
              #removeContact, [], {#areaId: areaId, #contact: contact}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<Map<String, dynamic>> addDevice({int? areaId, String? address}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #addDevice, [], {#areaId: areaId, #address: address}),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i3.Future<Map<String, dynamic>>);
  @override
  _i3.Future<void> removeDevice({int? areaId, int? deviceId}) =>
      (super.noSuchMethod(
          Invocation.method(
              #removeDevice, [], {#areaId: areaId, #deviceId: deviceId}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> executeDeviceAction(
          {int? areaId, int? deviceId, int? deviceActionId}) =>
      (super.noSuchMethod(
          Invocation.method(#executeDeviceAction, [], {
            #areaId: areaId,
            #deviceId: deviceId,
            #deviceActionId: deviceActionId
          }),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
}
